#!/bin/sh
# generate a lot of pseudo-random data faster than /dev/random or /dev/urandom

openssl enc -aes-256-cbc -pass pass:"$(dd if=/dev/urandom bs=128 count=1 2>/dev/null | base64)" -nosalt  < /dev/zero
