#!/bin/sh
# Watch disk temperatures

sl=60
rep=30

hdr=
for i in /dev/sd[abcd]; do
	a=`hddtemp $i`
	d=`echo "$a" | cut -d: -f1`
	ty=`echo "$a" | cut -d: -f2`
	hdr="$hdr"`printf "%15s" $d`
done

date
echo "$hdr"
hc=0

while :; do
	l=
	for i in /dev/sd[abcd]; do
		a=`hddtemp $i`
		te=`echo "$a" | cut -d: -f3`
		l="$l"`printf "%15s" $te`
	done
	echo "$l"
	sleep $sl
	hc=$(($hc+1))
	if [ "$hc" -ge "$rep" ]; then
		date
		echo "$hdr"
		hc=0
	fi
done
