#!/bin/sh
## Show first 4 random local branches

n=4
g=''

if [ -z "$1" ]; then
	g='.'
fi

if [ "$1" == "-a" -o "$1" == "-r" ]; then
	bflags="$1"
	shift
fi

git branch $bflags | grep -v '^[+*]' | grep -i $g "$@" | shuf | head -n "$n"
