#!/bin/bash
## Edit a commit message of a given commit (rebase and --amend).

CID="$1"

if [ -z "$CID" ]; then
	echo "Usage: $0 <commit>"
	exit 1
fi

MYBRANCH=$(git branch | gawk '/^\* / { print $2 }')
TMPBRANCH="tmp-commit-edit.$$"

echo "FINALIZE BY:" git rebase --onto "$TMPBRANCH" "$CID" "$MYBRANCH"
git checkout -f -b "$TMPBRANCH" "$CID"

git commit --amend -v

echo git rebase --onto "$TMPBRANCH" "$CID" "$MYBRANCH"
git rebase --onto "$TMPBRANCH" "$CID" "$MYBRANCH" || { echo did not work for some reason, fix and rerun the command above; exit 1; }
git branch -d "$TMPBRANCH"

echo "done."
