#!/bin/sh
# Delete local branch and from common remotes (gh, gl) in the background

if [ -z "$1" ]; then
	echo "Gimme branch"
	exit 1
fi

default='gh'
other='gl'
echo "=== Kill local branch $1"
git branch -D "$1"
br="$1"
shift
# from all by default
if [ -z "$1" ]; then
	echo "=== Kill from remote $default (background)"
	git push $default :"$br" >& /dev/null &
	for i in $other; do
		echo "=== Kill from remote $i (background)"
		git push $i :"$br" >& /dev/null &
	done
	exit
fi
# from selected
while [ $# -ge 1 ]; do
	echo "=== Kill from remote $1 (background)"
	git push "$1" :"$br" >& /dev/null
	shift
done
