#!/bin/sh
# force push current branch to remote 'gh' that's presumably github,
# or push the given branch without force

function current_branch() {
	git_dir=$(git rev-parse --git-dir 2> /dev/null) || exit 1
	ref=$(git symbolic-ref HEAD 2> /dev/null) || exit 1
	br=${ref#refs/heads/}
	echo "$br"
}

if [ $# = 0 ]; then
	br=$(current_branch)
	echo "GITHUB: Silently forced push of $br"
	git push gh +"$br"
	exit
fi

echo "GITHUB: push $br"
echo git push gh "$@"
git push gh "$@"
