#!/bin/sh
# force push branch to remote 'repo' that's presumably repo.or.cz

function current_branch() {
	git_dir=$(git rev-parse --git-dir 2> /dev/null) || exit 1
	ref=$(git symbolic-ref HEAD 2> /dev/null) || exit 1
	br=${ref#refs/heads/}
	echo "$br"
}

if [ $# = 0 ]; then
	br=$(current_branch)
	echo "REPO: Silently forced push of $br"
	git push repo +"$br"
	exit
fi

echo git push repo "$@"
git push repo "$@"
