#!/bin/sh
# force push current branch to remote 'gl' that's presumably gitlab instance,
# or push the given branch without force

function current_branch() {
	git_dir=$(git rev-parse --git-dir 2> /dev/null) || exit 1
	ref=$(git symbolic-ref HEAD 2> /dev/null) || exit 1
	br=${ref#refs/heads/}
	echo "$br"
}

if [ $# = 0 ]; then
	br=$(current_branch)
	echo "GITLAB: Silently forced push of $br"
	git push gl +"$br"
	exit
fi

echo "GITLAB: push $br"
echo git push gl "$@"
git push gl "$@"
