#!/bin/sh
# force push branch to remote 'gh' that's presumably github

function current_branch() {
	git_dir=$(git rev-parse --git-dir 2> /dev/null) || exit 1
	ref=$(git symbolic-ref HEAD 2> /dev/null) || exit 1
	br=${ref#refs/heads/}
	echo "$br"
}

if [ $# = 0 ]; then
	br=$(current_branch)
	echo "GH: Silently forced push of $br"
	git push gh +"$br"
	exit
fi

echo git push gh "$@"
git push gh "$@"
