#!/bin/sh
# after a rejected patch, process all .rej files, open in split with original
# add afterwards (git, quilt)

function processfile() {

f="$1"

if ! [ -f "$f" ]; then
	echo "$0: file.rej"
	exit 1
fi

rej="$f"
f=${rej%%.rej}
porig="$f.porig"

if ! [ -f "$f" ]; then
	echo "ERROR: file $f not found"
	exit 1
fi

mode=o
if [ $(stty size|cut -d\  -f 2) -gt 160 ]; then
	echo "Vertical mode"
	mode=O
fi

quilt add "$f"

vi -$mode "$f" "$rej"

echo "Was the merge succesful? [y/n]"
read -n 1 r
echo

if [ "$r" = 'y' ]; then
	echo adding file for git commit:
	echo "CMD: git add $f"
	git add "$f"
	echo "deleting reject file $rej"
	rm -f -- "$rej" "$porig"
else
	echo "Not deleting $rej, git index untouched"
fi

}

if [ "$#" = 0 ]; then
	echo "find *.rej"
	for i in $(find . -type f -name '*.rej'); do
		processfile "$i"
	done
else
	echo "use cmdline files"
	for i in "$@"; do
		processfile "$i"
	done
fi
