#!/bin/sh
## Prettyfier of objdump assembly (AT&T, nice line graphics)

# One-liner:
#objdump --disassembler-options=suffix --insn-width=12 --visualize-jumps=extended-color -dr "$@" | c++filt | less

color='--disassembler-color=extended'
jumps="--visualize-jumps=extended-color"
insns="--insn-width=12"
prefix=""
default=""

while getopts "cijp" arg; do
	case "$arg" in
		h)
			echo "Usage: $0 [-cijp] objectfile"
			exit
			;;
		c) color= ;;
		i) insns="--no-show-raw-insn" ;;
		j) jumps= ;;
		p) prefix="--prefix-addresses" ;;
	esac
done
shift $((OPTIND-1))

# https://symbl.cc/en/unicode/blocks/box-drawing/
# !separation matters, order matters!
objdump "$default" "$color" "$prefix" "$insns" "$jumps" \
	-M suffix \
	-dr "$@" | c++filt |
	sed -e 's/\s+[\/,]-/┌─/' |
	sed -e 's/\s+[\/,]\([^m]*m\)-/┌\1─/' |
	sed -e 's/\([^m]*m\),\([^m]*m\)/\1┌\2/' |
	sed -e "s/[\\']/└/g" |
	sed -e 's/|/│/g' |
	sed -e 's/---/───/g' |
	sed -e 's/--/──/g' |
	sed -e 's/─-/──/g' |
	sed -e 's/─\([^m]*m\)-/─\1─/g' |
	sed -e 's/-\([^m]*m\)-/─\1─/g' |
	sed -e 's/->/─>/' |
	sed -e 's/-\([^m]*m\)>/─\>/' |
	sed -e 's/[+>]─/├─/' |
	sed -e 's/[+>]\([^m]*m\)─/├\1─/' |
	sed -e 's/m,/mY/' |
	less
