#!/bin/sh
# usage: $0 [struct] <type to search> [<member>]

## Open vim with coccigrep search, save temporary output for repeated calls
## NOTE: upstream coccigrep stopped working for some reason, this is a simpler
## version that does not find all occurrences.

para=`grep -c ^processor /proc/cpuinfo`
tmp=/tmp/coccigrep.$$$RANDOM.txt
tmpcocci=/tmp/coccigrep.$$$RANDOM.txt
memb=
stru=

if [ -z "$1" ]; then
	echo "Usage: $0 struct [member] [other args to coccigrep]"
	exit 1
fi

# $0 struct mystruct member
if [ "$1" = 'struct' ]; then
	stru="struct $2"
	shift
	shift
elif [[ $1 =~ ^struct ]]; then
	stru="$1"
	shift
else
	stru="struct $1"
	shift
fi

if ! [ -z "$1" ]; then
	memb="$1"
	shift
fi

echo "Running coccigrep with $para jobs to $tmp"
echo "RUN: coccigrep -p $para --vim -t $stru $memb $@ *.[ch] > $tmp"
#coccigrep -p $para --vim -t "$stru" $memb "$@" *.[ch] > "$tmp"

echo "@@
$stru *STRUCT;
@@
* STRUCT->$memb" > "$tmpcocci"

cat "$tmpcocci"

spatch --quiet --jobs $para -sp_file "$tmpcocci" -dir . -include_headers -U 0 |
	awk 'BEGIN{fn="NONE";ln=0;}
		/^---/ { fn=$2; }
		/^@@/ { ln=$2; ln=-ln; printf("%s:%d:1\n",fn,ln); }' \
	> "$tmp"

rm -- "$tmpcocci"

echo "Using $tmp for results, run   vim -q $tmp"
vim -q "$tmp"
