#!/bin/sh
# vim grep all *.[ch] files in current directory and open (:cNext/:cnext)

[ -z "$1" ] && { echo "usage: $0 regex"; exit 1; }

if [ -z "$2" ]; then
	vi -c ':grep "'"$@"'" *.[ch]'
else
	shift
	regex="$1"
	vi -c ":grep \"$regex\" $*"
fi
