#!/bin/sh
# translate "file:line:col" format to "vim +line file", to open files from eg.
# make output

# arch/x86/ia32/sys_ia32.c:438: error: unsupported inline asm: input constraint with a matching output constraint of incompatible type!
args=( $(echo "$@" | awk 'BEGIN{FS=":"} {print $1 " " $2}') )
exec ${EDITOR:-vim} "${args[0]}" "+${args[1]}"
