#!/bin/sh
## Add reviewed-by tag from known people to the right location to the top commit.

update=cat
update='git commit --amend -F -'

me='Reviewed-by: David Sterba <dsterba@suse.com>'
itsme=0

if [ -z "$1" -o "$1" = 'me' ]; then
	rev="$me"
	itsme=1
elif [ "$1" = 'anand' ]; then
	rev='Reviewed-by: Anand Jain <asj@kernel.org>'
elif [ "$1" = 'qu' ]; then
	rev='Reviewed-by: Qu Wenruo <wqu@suse.com>'
elif [ "$1" = 'filipe' ]; then
	rev='Reviewed-by: Filipe Manana <fdmanana@suse.com>'
elif [ "$1" = 'josef' ]; then
	rev='Reviewed-by: Josef Bacik <josef@toxicpanda.com>'
elif [ "$1" = 'johannes' -o "$1" = 'jth' ]; then
	rev='Reviewed-by: Johannes Thumshirn <johannes.thumshirn@wdc.com>'
elif [ "$1" = 'goldwyn' ]; then
	rev='Reviewed-by: Goldwyn Rodrigues <rgoldwyn@suse.com>'
elif [ "$1" = 'hch' ]; then
	rev='Reviewed-by: Christoph Hellwig <hch@lst.de>'
elif [ "$1" = 'naohiro' ]; then
	rev='Reviewed-by: Naohiro Aota <naohiro.aota@wdc.com>'
elif [ "$1" = 'boris' ]; then
	rev='Reviewed-by: Boris Burkov <boris@bur.io>'
elif [ "$1" = 'neal' ] ; then
	rev='Reviewed-by: Neal Gompa <neal@gompa.dev>'
elif [ "$1" = 'dan' ] ; then
	rev='Reviewed-by: Daniel Vacek <neelx@suse.com>'
else
	echo "ERROR: Unrecognized name: $1"
	exit 1
fi

git log --pretty=format:"%s%n%n%b" HEAD^..HEAD  |
awk -v tag="$rev" -v itsme="$itsme" -v printed=0 \
'
/Signed-off-by/ {
	if ($0 ~/Sterba/) {
		if (itsme) {
			if (!printed) print tag;
			printed=1;
		} else {
			if (!printed) print tag;
			printed=1;
		}
	} else {
		if (itsme) {
		} else {
			if (!printed) print tag;
			printed=1;
		}
	}
}
/David Sterba/ {
	if ($0 ~ /^.igned-off-by:.*Sterba/) {
		if (!printed) print tag;
		printed=1;
	}
}
{
	print $0;
}' |
	$update
