#!/bin/sh
## Create btrfs snapshot with a timestamp in name.

if ! [ -d "$1" ]; then
	echo "$1 does not exist"
	exit 1
fi

ts=$(date +%F-%T)
sudo btrfs subvolume snapshot "$1" "$1"-$ts || exit 1
sudo chown --reference="$from" "$to"
sudo chmod --reference="$from" "$to"
