#!/bin/sh
## Clear all X clipboards

xclip -i -selection primary < /dev/null
xclip -i -selection secondary < /dev/null
xclip -i -selection clipboard < /dev/null
xclip -i -selection buffer-cut < /dev/null
