#!/bin/sh
## Split panel, 2 lines at the bottom just to see the command but not the output,
## exit afterwards.

pwd=`pwd`
cmd="$@"
# Must be $* due to wide "..."
tmux splitw -v -d -l 2 "echo PWD: '$pwd' CMD: '$cmd'; $*"
