#!/bin/sh
## Install a few testing packages.

zypper install --force -l \
	ffsb \
	fs_mark \
	fio \
	mmtests \
	blogbench \
	sysbench \
	dbench \
	btrfsprogs \
	xfstests \
	xfsprogs \
	e2fsprogs \
	dt \
	blktrace \
	compilebench
