#!/bin/sh

dbg=true
dbg=false
tolerance=true

for f in *; do
	case "$f" in
		*.x265.mp4) continue;;
		*.x264.mkv) continue;;
		*.mp4)
			fext="${f}.x265.mp4"
			if ! [ -f "$fext" ]; then
				echo "Converted not found: $f"
				continue
			fi
			$dbg && echo "FILE: $f"
			d1=$(ff-info "$f" 2>&1 | grep Duration | sed -e 's/start:.*//')
			d2=$(ff-info "$fext" 2>&1 | grep Duration | sed -e 's/start:.*//')
			dt1=$(echo "$d1" | sed -e 's/[0-9][0-9],.*//')
			dt2=$(echo "$d2" | sed -e 's/[0-9][0-9],.*//')
			#d2=$(echo "$d2" | sed -e 's/00:/11:/')
			$dbg && echo "-- $d1 / $dt1"
			$dbg && echo "-- $d2 / $dt2"
			if ! [ "$d1" = "$d2" ]; then
				if $tolerance && [ "$dt1" = "$dt2" ]; then
					continue
				fi
				echo "NOT OK: $f"
				echo "time 1: $d1"
				echo "time 2: $d2"
				echo
			fi
			;;
		*) continue;;
	esac
done
