#!/bin/sh -x

in="$1"

codec=libx265
crf=28
q=720

if [ -z "$in" ]; then
        echo "usage: $0 infile"
        exit 1
fi

ffmpeg -hide_banner -i "$in" -c:v $codec -crf $crf -vf scale=-2:$q -c:a libmp3lame -q:a 2 "$in".${q}p.mp4
